### ISSUE TITLE
Cannot successfully deploy most basic sample from Documentation

### ISSUE THREAD

**Issue by madorb** [spring-cloud/spring-cloud-deployer-kubernetes#180] opened 2018-02-07 23:54 UTC
Please forgive me if this is not the right project for this, but given the number of overall projects, it's hard for someone brand new to identify where the issue may lie. 

Long story short is that I'm following the SCDF Kubernetes documentation as here:

https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.3.0.RELEASE/reference/htmlsingle/#getting-started-deploying-streams

but I'm unsuccessful in deploying even the most basic use case. I've tried this on both Docker w/ Kubernetes as well as MiniKube. 

Full steps to reproduce:

* install minikube & launch with `minikube start --cpu 4 --memory 8196`
* `git clone https://github.com/madorb/spring-cloud-dataflow-server-kubernetes.git`
* `cd spring-cloud-dataflow-server-kubernetes`
* Deploy all the required components
```
kubectl create -f src/kubernetes/rabbitmq;
kubectl create -f src/kubernetes/mysql/;
kubectl create -f src/kubernetes/redis/;
kubectl create -f src/kubernetes/metrics/metrics-deployment-rabbit.yaml;
kubectl create -f src/kubernetes/metrics/metrics-svc.yaml;
kubectl create -f src/kubernetes/server/server-roles.yaml;
kubectl create -f src/kubernetes/server/server-rolebinding.yaml;
kubectl create -f src/kubernetes/server/service-account.yaml;
kubectl create -f src/kubernetes/server/server-config-rabbit.yaml;
kubectl create -f src/kubernetes/server/server-svc.yaml;
kubectl create -f src/kubernetes/server/server-deployment.yaml;
```
* `java -jar spring-cloud-dataflow-shell-1.3.0.RELEASE.jar`
* connect to scdf-server
* `app register --type source --name time --uri docker://springcloudstream/time-source-rabbit:1.3.1.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:time-source-rabbit:jar:metadata:1.3.1.RELEASE`
* `app register --type sink --name log --uri docker://springcloudstream/log-sink-rabbit:1.3.1.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.3.1.RELEASE`
* `stream create --name ticktock --definition "time | log" --deploy`
* wait for a short bit and run `kubectl get all` and note that we don't have apod for the ticktock-log 
* finally run `kubectl describe statefulsets/ticktock-log`

```
Events:
  Type     Reason        Age                From                    Message
  ----     ------        ----               ----                    -------
  Warning  FailedCreate  5s (x12 over 16s)  statefulset-controller  create Pod ticktock-log-0 in StatefulSet ticktock-log failed error: Failed to create PVC ticktock-log-ticktock-log-0: PersistentVolumeClaim "ticktock-log-ticktock-log-0" is invalid: spec.resources[storage]: Invalid value: "0": must be greater than zero
  Warning  FailedCreate  3s (x13 over 16s)  statefulset-controller  create Claim ticktock-log-ticktock-log-0 for Pod ticktock-log-0 in StatefulSet ticktock-log failed error: PersistentVolumeClaim "ticktock-log-ticktock-log-0" is invalid: spec.resources[storage]: Invalid value: "0": must be greater than zero
```

Additional info:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by madorb** [comment] 2018-02-08 17:46
Looks like this is likely to be resolved by https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/181...

**Comment by markpollack** [comment] 2018-02-09 15:07
Sorry about this, pretty embarassing as our tests weren't against the most recent version of k8s...which is what we think ATM is the root cause of why all our integration test passed.  Will look to resolve this ASAP!  Thanks for reporting.

**Comment by sabbyanandan** [comment] 2018-02-13 14:37
This is addressed in spring-cloud/spring-cloud-deployer-kubernetes#181.

**Closed by sabbyanandan** 2018-02-13 14:37 UTC
Labels: ready
